### PR TITLE
migrated old qpn branch-specific code to new qpn fork (the correct one this time!) 

### PR DESCRIPTION
**Pull request by nikhil153**

### CODE REVIEW

**Comment by michellewang** [comment]
@nikhil153 `collate_freesurfer_stats.py` is currently also in `mr_proc` ([here](https://github.com/neurodatascience/mr_proc/blob/main/analysis/freesurfer/collate_freesurfer_stats.py)). Is this a QPN-specific script? If that's the case we should remove it from https://github.com/neurodatascience/mr_proc first to prevent merge conflicts. Otherwise if this is a common script across datasets then we should change it in https://github.com/neurodatascience/mr_proc instead of the QPN fork.

**Comment by nikhil153** [comment]
@michellewang - it's not QPN specific. It's a general script to parse FreeSurfer CT data. 
I see mr_proc* repo has a duplicate of this. I will delete it from there since now we are replacing dir-name `freesurfer` with `CT` within the `analysis` dir - which is what this PR has.

**Comment by michellewang** [comment]
@nikhil153 if it's a common script that should be on both PPMI and QPN forks, shouldn't we do something like this instead?
* Delete `analysis/CT/collate_freesurfer_stats.py` from this PR
* Make a new PR on mr_proc* to move `analysis/freesurfer/collate_freesurfer_stats.py` to `analysis/CT/collate_freesurfer_stats.py`
  * This way the changes will sync down to PPMI and QPN forks. Otherwise for PPMI to have the same script we would have to manually copy it, which we should try to avoid

Although if I remember correctly, I think we previously said that `analysis` shouldn't have any common code. Maybe this would fit better in a new `extractor` subdirectory? (Does this count as an extractor?)

**Comment by nikhil153** [comment]
@michellewang - True! We did say we will keep `analysis` dataset-specific. This is what I will do. 

1. Delete `analysis/CT/collate_freesurfer_stats.py` from this PR
2. Rename / move the `analysis/freesurfer/collate_freesurfer_stats.py` from mr_proc* to `extractor/freesurfer/collate_freesurfer_stats.py` 

Thanks for catching this!

**Comment by michellewang** [comment]
@nikhil153 is `analysis/FC/fmriprep2func_conn.py` also QPN-specific? It seems like it can be generalized to any fMRIPrep output (is it also a kind of extractor?). I know we haven't downloaded/converted the PPMI functional data yet but we still might want to put that script in `mr_proc*` for eventual use in other datasets.

Also, I'm not sure we should commit the `BNT_norming_config.json` and `DSF_norming_config.json` because people would have to change them locally and then would get annoying merge conflicts whenever they try to pull from GitHub (this happened to me with the `bids_filter.json` when running fMRIPrep). Maybe we could have a `sample_BNT_norming_config.json` and a `sample_DSF_norming_config.json` that people can copy and just change the path fields. Or (probably better) refactor to use the global config file.

**Comment by nikhil153** [comment]
> analysis/FC/fmriprep2func_conn.py also QPN-specific?
This is a question for @mtorabi59! 
>I'm not sure we should commit the BNT_norming_config.json and DSF_norming_config.json because people would have to change them locally
True - but these are serving as reference to the QPN neuropsych lab and I needed a place to keep them before deleting the old QPN branch. Eventually I will create a `sample_config.json` but not sure how that would look at the moment. 
>We should also probably (eventually) refactor the manifest creation and the two tracking notebooks into scripts.
Hehe yes! I have tried that a couple times already, but QPN naming keeps changing :( so notebooks are just easier for quick checks and updates.

**Comment by mtorabi59** [comment]
@michellewang yes `analysis/FC/fmriprep2func_conn.py` can be used for any fmriprep output. It depends if we want to use it for other data in future.

**Review by michellewang — APPROVED** [review]

**Pull request merged**
